// =====================================================
// EXPORT UTILITIES — PDF, Excel, Share Text
// =====================================================

/**
 * Generate plain-text bill for native share
 */
export function generateBillText({ vendorName, customerName, month, entries, rate, total, advance, balance }) {
  const lines = [
    `🏠 Ghar Ka Hisab`,
    `━━━━━━━━━━━━━━━━━━━━`,
    `Vendor: ${vendorName}`,
    customerName ? `Customer: ${customerName}` : '',
    `Month: ${month}`,
    `━━━━━━━━━━━━━━━━━━━━`,
    ...entries.map(e => `${e.date}  ${e.qty} × ₹${rate} = ₹${(e.qty * rate).toFixed(2)}`),
    `━━━━━━━━━━━━━━━━━━━━`,
    `Total: ₹${total}`,
    advance != null ? `Advance: ₹${advance}` : '',
    balance != null ? `Baki: ₹${Math.abs(balance)} ${balance < 0 ? '(Due)' : '(Credit)'}` : '',
    `━━━━━━━━━━━━━━━━━━━━`,
    `Generated by Ghar Ka Hisab App`,
  ].filter(Boolean);

  return lines.join('\n');
}

/**
 * Generate grocery list text for sharing
 */
export function generateGroceryText(items) {
  const header = `🛒 Grocery List — Ghar Ka Hisab\n${'─'.repeat(30)}\n`;
  const rows = items.map((it, i) => `${i + 1}. ${it.name}  ${it.qty} ${it.unit}  ₹${it.price || ''}`).join('\n');
  return header + rows + `\n${'─'.repeat(30)}\nTotal Items: ${items.length}`;
}

/**
 * Native share via Web Share API or clipboard fallback
 */
export async function nativeShare(text, title = 'Ghar Ka Hisab') {
  if (navigator.share) {
    try {
      await navigator.share({ title, text });
      return true;
    } catch (e) {
      // User cancelled or not supported
    }
  }
  // Fallback: copy to clipboard
  try {
    await navigator.clipboard.writeText(text);
    return 'clipboard';
  } catch {
    return false;
  }
}

/**
 * Export to PDF using jsPDF
 */
export async function exportToPDF(title, rows, footer = '') {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const margin = 15;
  let y = 20;

  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text('🏠 Ghar Ka Hisab', margin, y);
  y += 8;

  doc.setFontSize(14);
  doc.text(title, margin, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, margin, y);
  y += 8;

  // Table header
  doc.setFillColor(26, 5, 51);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.rect(margin, y, 180, 7, 'F');
  const headers = Object.keys(rows[0] || {});
  headers.forEach((h, i) => {
    doc.text(String(h), margin + 2 + i * (180 / headers.length), y + 5);
  });
  y += 9;

  // Rows
  doc.setTextColor(40, 40, 40);
  for (const row of rows) {
    if (y > 270) { doc.addPage(); y = 20; }
    const vals = Object.values(row);
    if (rows.indexOf(row) % 2 === 0) {
      doc.setFillColor(245, 245, 255);
      doc.rect(margin, y - 1, 180, 7, 'F');
    }
    vals.forEach((v, i) => {
      doc.text(String(v ?? ''), margin + 2 + i * (180 / vals.length), y + 4);
    });
    y += 7;
  }

  if (footer) {
    y += 4;
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(footer, margin, y);
  }

  const filename = `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
  return filename;
}

/**
 * Export to Excel using SheetJS
 */
export async function exportToExcel(sheetName, rows) {
  const XLSX = await import('xlsx');
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  const filename = `${sheetName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.xlsx`;
  XLSX.writeFile(wb, filename);
  return filename;
}
